---
- hosts: webserverhost
  become: yes
  tasks:
      - name: install java 8 version on ubuntu node
        apt: 
            name: openjdk-8-jre
            state: present
        when: ansible_os_family=="Debian"


      - name: install java 8 version on RedHat node
        yum:
            name: java-1.8.0-openjdk
            state: present
        when: ansible_os_family=="RedHat"

