---
- hosts: webserverhost
  become: yes
  tasks:
      - name: install java 8 version on ubuntu node
        apt: 
            name: "{{myjavapackageforubuntu}}"
            state: present
        when: ansible_os_family=="Debian"


      - name: install java 8 version on RedHat node
        yum:
            name: "{{myjavapackageforredhat}}"
            state: present
        when: ansible_os_family=="RedHat"

