--- 
- hosts: all 
  become: yes
  tasks:
        - name: install webserver on ubuntu node
          apt: 
                  name: apache2
                  state: present
          when: ansible_os_family=="Debian"             


        - name: start/stop webserver
          service:
                  name: apache2
                  state: started
          when: ansible_os_family=="Debian"


        - name: install webserver on RedHat node 
          yum:
                  name: httpd
                  state: present
          when: ansible_os_family=="RedHat"

        - name: start/ stop RedHat webserver
          service:
                   name: httpd
                   state: started              
          when: ansible_os_family=="RedHat"
