---
# tasks file for mywebrole
- name: i want to install apache2
  apt:
   name: apache2
   state: present
  notify: restartwebserver



- name: i want to change template
  template:
    src: template/index.j2
    dest:  /var/www/html/index.html
  notify: restartwebserver